### ISSUE TITLE
Different syntax in App.css

### ISSUE THREAD

**Issue by olivierobert** [Yutna/nimble-tech-test#3]
It seems like the stylesheet for `App.css` does not follow the same formatting as the other stylesheets. Be consistent 🤓

![app_css_-_yutna_-___volumes_workspace__candidates-tests_yutna_](https://user-images.githubusercontent.com/696529/33262166-f3391258-d397-11e7-9ca9-55834d95a072.png)

The other files (our preferred syntax as well):

![button_index_scss_-_yutna_-___volumes_workspace__candidates-tests_yutna_](https://user-images.githubusercontent.com/696529/33262198-0bd9453a-d398-11e7-9f9d-f006a3c4148b.png)

**Comment by Yutna** [comment]
App.css is not original source file. It is compiled file from App.scss. I think this may be not an issue.

**Comment by olivierobert** [comment]
Yes correct 😅
